[build-system]
requires = ['setuptools', 'numpy', 'scipy', 'Cython']
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 120
skip-string-normalization = true

# FIXME: coverage can't reach lines of numba.njit-ed functions
[tool.coverage.run]
omit = ['imops/src/_numba_zoom.py']

[tool.isort]
line_length = 120
lines_after_imports = 2
profile = 'black'
combine_as_imports = true
