[build-system]
requires = [
    'setuptools',
    'numpy',
    "numpy==1.22.3; python_version=='3.10' and platform_machine=='win32' and platform_python_implementation != 'PyPy'",
    "numpy==1.21.6; python_version=='3.10' and (platform_machine!='win32' and platform_machine!='loongarch64') and platform_python_implementation != 'PyPy'",
    'scipy',
    'Cython'
]

build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.pytest.ini_options]
markers = [
    "nonumba",
]

[tool.isort]
line_length = 120
lines_after_imports = 2
profile = 'black'
combine_as_imports = true
