name: Test build

on: [ pull_request ]

env:
  MODULE_NAME: imops

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019, macOS-12 ]

    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_TEST_REQUIRES: pytest numpy
          CIBW_TEST_COMMAND: pytest {project}/tests
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_BUILD: ${{ matrix.build }}
      # - name: Build wheels
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install wheel setuptools pip --upgrade
      #     python -m cibuildwheel --output-dir wheelhouse
      - name: Check with Twine
        run: |
          pipx run twine check wheelhouse/*
        env:
          # CIBW_ENVIRONMENT_MACOS: >
          #   PATH="/usr/local/opt/llvm/bin:$PATH" LDFLAGS="-L/usr/local/opt/llvm/lib" CPPFLAGS="-I/usr/local/opt/llvm/include" CC="/usr/local/opt/llvm/bin/clang"
          CIBW_BUILD: cp37-* cp39-* cp312-*
          CIBW_SKIP: "*manylinux_x86_64"
          CIBW_BEFORE_BUILD_LINUX: 'if [ $(python -c "import sys; print(sys.version_info[1])") -ge 9 ]; then python -m pip install "numpy<3.0.0" --config-settings=setup-args="-Dallow-noblas=true"; fi'
